[package]
name = "boring_rpc_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
boring_rpc_syn = { version = "0.1.0", path = "../boring_rpc_syn" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"

[dev-dependencies]
expect-test = "1.5.0"
